### ISSUE TITLE
Look into how Paul Czarkowski deploys to the CS

### ISSUE THREAD

**Issue by krook** [krook/nginx-php-container-cluster#13]
Probably some minikube, Helm, Tiller, Maven tips to learn from this:

https://github.com/IBM/activator-lagom-java-chirper/tree/master/docs

**Comment by jzaccone** [comment]
I looked into using Helm and Tiller for deployment. I think we agreed that it would add another layer of complexity for a learning example. Maven is similar deal. Close @krook ?

**Comment by krook** [comment]
Agree. Thanks @jzaccone
