### ISSUE TITLE
Implement the DevOps pipeline

### ISSUE THREAD

**Issue by krook** [krook/nginx-php-container-cluster#14]
1. Commit to GitHub
2. Fire a webhook or other mechanism
3. Download code
4. Run Docker build
5. Push to registry
6. Rolling deploy to CS

**Comment by krook** [comment]
- Will need to try out the new Container Service plugin released 10/4
- Need to be able to use "bring-your-own-Docker-images"

**Comment by odrodrig** [comment]
Steps to implement a pipeline with the new "Container Registry" build step have been added under docs/PIPELINE-SETUP.md. 

Build and deploy scripts for pipeline have been added under scripts/pipeline
