### ISSUE TITLE
Update NGINX configuration for Drupal

### ISSUE THREAD

**Issue by krook** [krook/nginx-php-container-cluster#45]
This link has good info:  https://www.nginx.com/resources/wiki/start/topics/recipes/drupal

Other resources:
- https://www.drupal.org/docs/8/system-requirements/web-server
- http://nginx.org/en/docs/http/ngx_http_rewrite_module.html
- https://github.com/wodby/drupal-nginx

Steps required would be:
- Update the Dockerfile to build the NGINX image
- Update the start.sh file, if needed
- Run `cd docker/nginx`
- Run `docker build --tag registry.ng.bluemix.net/jjdojo/nginx:latest --no-cache .`
- Run `docker push registry.ng.bluemix.net/jjdojo/nginx:latest`
- Run `kubectl apply -f kubernetes/nginx.yaml` which should pull latest and restart

You might also have to do these steps if the above ones don't work.
- Update the deployment file to point to a new image name, if needed
- Delete the existing NGINX pod
- Bring up the new NGINX pod

**Comment by jzaccone** [comment]
`kubectl rolling-update` is the "old" way to do rolling updates via replicasets (before deployments came around). This command works:
```bash
kubectl set image deployment/simple-nginx simple-nginx=jzaccone/simple-nginx:latest
```

**Comment by krook** [comment]
@odrodrig demonstrated this as part of the build pipeline. @jzaccone also is working on Ingress in another issue.
